os:
  - osx
  - linux
language: node_js
node_js:
  - 6
  - 7
  - 8
  - node
install:
  - npm install
script:
  - npm test
  - npm run lint
after_success: npm run coveralls
notifications:
  email: false
